In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
rng = np.random.default_rng(seed = 42)

## 1. How likely is it that you roll doubles when rolling two dice?

In [3]:
rolls = rng.choice([1, 2, 3, 4, 5, 6], 10_000 * 2).reshape(10_000, 2)
rolls

array([[1, 5],
       [4, 3],
       [3, 6],
       ...,
       [5, 1],
       [1, 3],
       [3, 3]])

In [4]:
doubles = (rolls[:, 1] == rolls[:, 0]).sum()

In [5]:
doubles / len(rolls)

0.1712

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

## What is the probability of getting more than 3 heads?

In [6]:
#heads = 1
#tails = 0

flips = rng.choice([0, 1], 10_000 * 8).reshape(10_000, 8)
flips

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 0, 1]])

In [7]:
exactly_three = (flips.sum(axis=1) == 3).sum()
exactly_three

2201

In [8]:
exactly_three / len(flips)

0.2201

In [9]:
heads = (flips.sum(axis=1) > 3).sum()
heads

6398

In [10]:
heads / len(flips)

0.6398

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [16]:
c = rng.choice(['w', 'd'], 1_000 * 2, p = [.75, .25]).reshape(1_000, 2)
c

array([['w', 'w'],
       ['w', 'w'],
       ['w', 'w'],
       ...,
       ['w', 'w'],
       ['w', 'd'],
       ['w', 'w']], dtype='<U1')

In [21]:
b = ((c == 'd').sum(axis = 1) == 2).mean()
b

0.06

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [22]:
c = (rng.normal(3, 1.5, (1_000, 4))).sum(axis=1)
c

array([15.07870402, 15.07375009, 12.31014953, 12.59141279, 10.18679191,
       12.121697  ,  8.73268527, 17.66662422, 13.50924674, 12.25846529,
       18.27693396, 10.63817844, 14.36475106, 14.75789091,  6.82906071,
        4.1511074 , 10.77569864, 14.87406916, 10.6658563 , 16.24972289,
       13.39062424,  9.25907486,  9.06151624,  7.49717132,  7.12451254,
       19.26039234, 12.85716493, 10.47239034, 13.47940448,  8.40421658,
       10.07945501, 15.32295122,  8.29534283, 16.7143705 , 15.25218948,
       13.63304072, 10.44400859,  7.02509691, 13.68686349, 14.26578204,
       13.15115316,  4.55385928,  8.14220999, 13.81141545, 12.835758  ,
       14.70729657,  8.53153619, 11.8058973 , 11.46057743,  9.44417223,
       13.13114542, 12.32231335,  9.90374464, 11.62385221, 11.61570287,
       13.29953409, 11.1857559 , 10.78249841,  9.75868681, 16.29940343,
        8.87514278, 11.89529952, 10.63062792, 11.76971514, 14.19471539,
       12.4825145 , 12.16067122,  6.46321223,  8.97703069, 14.55

In [23]:
r = 17 - c
r 

array([ 1.92129598,  1.92624991,  4.68985047,  4.40858721,  6.81320809,
        4.878303  ,  8.26731473, -0.66662422,  3.49075326,  4.74153471,
       -1.27693396,  6.36182156,  2.63524894,  2.24210909, 10.17093929,
       12.8488926 ,  6.22430136,  2.12593084,  6.3341437 ,  0.75027711,
        3.60937576,  7.74092514,  7.93848376,  9.50282868,  9.87548746,
       -2.26039234,  4.14283507,  6.52760966,  3.52059552,  8.59578342,
        6.92054499,  1.67704878,  8.70465717,  0.2856295 ,  1.74781052,
        3.36695928,  6.55599141,  9.97490309,  3.31313651,  2.73421796,
        3.84884684, 12.44614072,  8.85779001,  3.18858455,  4.164242  ,
        2.29270343,  8.46846381,  5.1941027 ,  5.53942257,  7.55582777,
        3.86885458,  4.67768665,  7.09625536,  5.37614779,  5.38429713,
        3.70046591,  5.8142441 ,  6.21750159,  7.24131319,  0.70059657,
        8.12485722,  5.10470048,  6.36937208,  5.23028486,  2.80528461,
        4.5174855 ,  4.83932878, 10.53678777,  8.02296931,  2.44

In [24]:
(r >= 0).mean()

0.943

## 5. Compare Heights

## * Men have an average height of 178 cm and standard deviation of 8cm.

## * Women have a mean of 170, sd = 6cm.

## * Since you have means and standard deviations, you can use np.random.normal to generate observations.

## * If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [29]:
m = (rng.normal(178, 8, 1_000))
m

array([176.52518702, 183.02128027, 177.7622856 , 181.14031056,
       175.12254781, 190.03822712, 176.13606276, 171.91016548,
       180.77574794, 171.32049368, 179.8786203 , 191.17670983,
       177.64146417, 167.16528986, 174.67910226, 184.49961302,
       178.85510087, 183.61029585, 172.93860421, 174.70431745,
       183.0691638 , 190.88718064, 174.90180333, 178.29918292,
       186.79924159, 179.04839641, 183.10218938, 172.07881656,
       178.02841702, 173.02894338, 164.51544137, 170.92425526,
       181.58567763, 182.41459215, 184.14873839, 182.07172175,
       176.22398593, 163.33517907, 168.84712253, 186.83796474,
       171.26287155, 177.40401408, 178.50200273, 166.91839524,
       180.65768077, 190.22224766, 177.84997288, 175.8456852 ,
       168.73287219, 175.80893284, 182.33011657, 177.94902945,
       174.48231521, 186.04718929, 175.90740541, 174.57725465,
       179.12967384, 188.45595062, 176.76368112, 170.91569329,
       182.36653566, 175.34594726, 182.43871226, 161.61

In [30]:
w = (rng.normal(170, 6, 1_000))
w

array([162.43635339, 174.00459494, 161.34227679, 174.48717459,
       176.92939633, 163.20846164, 167.79703111, 177.14140192,
       178.35128058, 161.43403224, 172.25967753, 173.92174576,
       169.94449952, 178.61646094, 166.71838385, 167.51063028,
       166.04498235, 171.47334199, 168.38832008, 175.23376044,
       167.91485916, 169.00529779, 171.51712327, 165.33519359,
       176.41706437, 174.4337966 , 174.23817546, 164.197538  ,
       179.59522892, 159.21209242, 174.76526356, 171.16467618,
       174.33194703, 169.0373839 , 170.83801046, 174.53059555,
       170.32722673, 171.62704499, 171.8221707 , 183.50075219,
       160.75118234, 178.11514227, 173.05344153, 172.30857218,
       162.70597356, 177.25312684, 163.53623354, 179.17274821,
       167.07415122, 179.17248794, 166.07922508, 164.73332396,
       169.74525881, 165.87010731, 168.9044446 , 180.43983859,
       166.99976861, 171.36478545, 179.87010938, 171.74995663,
       177.07433558, 173.65760514, 176.31302251, 169.91

In [31]:
wt = (w > m).sum()
wt

204

In [32]:
wt / len(w)

0.204

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

## * What is the probability that we observe an installation issue within the first 150 students that download anaconda?

## * How likely is it that 450 students all download anaconda without an issue?

In [33]:
c = 1 / 250
c

0.004

In [70]:
s = rng.random((1_000, 50))
len(s)

1000

In [71]:
ic = (s > c).sum(axis = 1)
ic

array([50, 50, 50, 50, 50, 50, 50, 49, 50, 50, 50, 50, 49, 50, 50, 50, 49,
       49, 48, 50, 50, 48, 50, 50, 49, 50, 49, 49, 50, 50, 50, 50, 50, 50,
       50, 49, 50, 49, 50, 49, 50, 50, 50, 50, 50, 50, 50, 49, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 49, 50, 49, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 49, 50, 50, 50, 50, 49, 50, 50, 50, 50, 50, 49, 50, 50, 50,
       50, 50, 50, 50, 49, 50, 49, 49, 50, 50, 50, 49, 50, 50, 49, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 49, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 49, 50, 50, 50, 50, 50,
       50, 49, 50, 50, 50, 50, 50, 49, 49, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 49, 50,
       50, 50, 50, 50, 50, 50, 49, 50, 50, 50, 50, 49, 49, 50, 50, 50, 50,
       50, 49, 50, 50, 50, 50, 50, 49, 50, 50, 49, 50, 49, 50, 49, 50, 50,
       50, 50, 50, 50, 50, 49, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       49, 50, 50, 50, 50

In [72]:
(ic == 50).sum() / len(s)

0.803

In [73]:
s = rng.random((1_000, 100))
len(s)

1000

In [59]:
ic = (s > c).sum(axis = 1)
ic

array([100, 100,  99, 100,  98, 100,  99, 100,  99,  98, 100,  99, 100,
       100, 100,  99,  99, 100,  97,  99,  99,  99,  98,  99, 100, 100,
       100, 100,  99, 100,  99, 100, 100,  99, 100, 100, 100, 100, 100,
       100, 100,  99, 100, 100, 100,  98, 100, 100,  99, 100,  99,  99,
       100, 100,  98, 100, 100, 100, 100,  98, 100, 100, 100,  99, 100,
       100,  99,  99, 100, 100, 100, 100, 100, 100,  99, 100, 100, 100,
       100,  98, 100, 100, 100, 100, 100,  99, 100,  99, 100,  99,  99,
        99, 100, 100, 100,  99, 100, 100,  99, 100,  99, 100,  99, 100,
       100, 100, 100, 100, 100,  99, 100, 100,  99, 100, 100, 100,  99,
       100,  99, 100,  98, 100, 100, 100, 100, 100, 100,  99, 100, 100,
        99, 100, 100, 100, 100,  99,  99, 100, 100, 100, 100,  98, 100,
       100, 100, 100,  99,  98, 100, 100,  99, 100, 100,  99, 100, 100,
        99, 100,  99, 100, 100, 100, 100, 100,  99, 100, 100,  98, 100,
       100,  99, 100, 100, 100, 100, 100, 100, 100,  99, 100,  9

In [65]:
1 - (ic == 100).sum() / len(s)

0.31699999999999995

In [67]:
s = rng.random((1_000, 150))
len(s)

1000

In [68]:
ic = (s > c).sum(axis = 1)
ic

array([150, 150, 149, 150, 150, 149, 150, 150, 149, 148, 150, 150, 150,
       150, 150, 149, 148, 149, 148, 150, 150, 150, 149, 148, 150, 150,
       149, 148, 150, 150, 150, 148, 150, 150, 150, 150, 150, 149, 150,
       148, 150, 149, 150, 150, 150, 149, 149, 150, 149, 150, 150, 150,
       150, 150, 149, 150, 149, 149, 150, 150, 149, 150, 147, 150, 150,
       150, 149, 150, 148, 150, 150, 149, 149, 148, 149, 150, 150, 149,
       150, 150, 150, 148, 148, 149, 149, 150, 150, 149, 149, 149, 149,
       147, 150, 150, 150, 147, 149, 150, 150, 149, 150, 150, 149, 148,
       150, 150, 149, 149, 150, 148, 149, 149, 148, 147, 149, 150, 150,
       150, 150, 150, 150, 150, 150, 150, 149, 149, 150, 150, 150, 149,
       149, 150, 148, 150, 150, 150, 148, 150, 150, 150, 150, 150, 150,
       149, 148, 150, 150, 150, 149, 150, 150, 150, 150, 149, 150, 150,
       150, 149, 150, 149, 149, 149, 148, 149, 150, 150, 150, 148, 150,
       150, 150, 150, 150, 150, 149, 149, 150, 150, 150, 149, 14

In [69]:
1 - (ic == 150).sum() / len(s)

0.45099999999999996

In [74]:
s = rng.random((1_000, 450))
len(s)

1000

In [75]:
ic = (s > c).sum(axis = 1)
ic

array([448, 446, 450, 448, 450, 448, 449, 450, 448, 446, 450, 448, 448,
       446, 447, 447, 447, 448, 442, 448, 449, 449, 446, 449, 450, 449,
       449, 448, 448, 448, 449, 449, 449, 449, 447, 447, 448, 450, 448,
       450, 447, 449, 447, 447, 450, 448, 449, 447, 446, 448, 446, 447,
       447, 450, 445, 447, 444, 449, 445, 449, 450, 447, 447, 446, 446,
       450, 449, 450, 447, 448, 448, 449, 445, 450, 449, 445, 450, 446,
       444, 448, 448, 446, 450, 443, 450, 447, 448, 449, 449, 447, 447,
       449, 449, 450, 448, 449, 449, 449, 448, 449, 447, 448, 449, 448,
       448, 448, 448, 450, 448, 449, 449, 450, 448, 450, 445, 448, 447,
       447, 448, 450, 446, 448, 449, 450, 450, 450, 447, 448, 449, 449,
       449, 443, 445, 447, 450, 446, 449, 450, 449, 447, 448, 450, 449,
       450, 449, 448, 449, 450, 449, 447, 448, 442, 449, 447, 447, 450,
       446, 449, 449, 447, 448, 449, 448, 447, 449, 449, 449, 447, 447,
       450, 449, 447, 449, 447, 449, 448, 448, 447, 449, 446, 44

In [78]:
(ic == 450).sum() / len(s)

0.155

## There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [79]:
truck = rng.choice([0, 1], size = (1_000, 3), p = [.3, .7])
truck

array([[1, 1, 1],
       [0, 1, 0],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [80]:
(truck.sum(axis = 1) == 0).mean()

0.023

## How likely is it that a food truck will show up sometime this week?

In [81]:
(truck.sum(axis = 1) >= 1).mean()

0.977

## If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [89]:
birthday = rng.choice(range(0, 365), size = (1_000, 23))

In [90]:
df = pd.DataFrame(birthday)

In [91]:
df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  130  353   16  142  144   46   83  206  364  184  ...  275  117  133  127   
1  225   54  162   27  170  235   33  293  212  262  ...   54  364   58   59   
2   57   18  226  209   72  282  170  255  220  239  ...  319  133   12  307   
3  129   43  117  171  194  354  265  267  236  251  ...  191  282   74  144   
4    9  193  268  291   50  253  117  210   39  358  ...   39  294   67  168   

    17   18   19   20   21   22  
0  330   40   48  185  352   21  
1  336   40  259   72  159  128  
2   43  110  220   32  107  306  
3   14  169   25  216  303   44  
4  166  206  185   95   32  205  

[5 rows x 23 columns]

In [95]:
(df.nunique(axis = 1) < 23).mean()

0.495

In [104]:
birthday = rng.choice(range(0, 365), size = (1_000, 20))

In [105]:
df = pd.DataFrame(birthday)

In [106]:
df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0   71  234  256  228  254  224  310   72   55    0   62  114  329  252   75   
1  155  231  363  198  227  183  270  263  218  140  213   96  148  308  343   
2  320  358   73  349  170  155   75  340  167  301   57  163  276   85   56   
3   58  190  245  147   29  274  197  102  136  333  168  178   36   45  143   
4  229  336    5   25  260   33  236  323  131  360  153   40  238  244  334   

    15   16   17   18   19  
0  284  345  348  330  327  
1   69  258  256  311  329  
2  114   56  315  207   30  
3  125  121   15  150  237  
4   12  104  147   97  232

In [107]:
(df.nunique(axis = 1) < 20).mean()

0.409

In [108]:
birthday = rng.choice(range(0, 365), size = (1_000, 40))

In [109]:
df = pd.DataFrame(birthday)

In [110]:
df.head()

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0  272  245   52  180  353  242  157   93  317  171  ...  315  246  153  319   
1  252   82  187  340  197  235  176  323  197  152  ...  141  233  299   83   
2   22   64  239  300   43  292  149  123  229  107  ...  244  340  322  129   
3  311  106  111   99  168  174   66  224  235  284  ...  261  134   99  222   
4  358  114   47  344  302  310   96  113  109  358  ...   81  322   43  153   

    34   35   36   37   38   39  
0  149   80  204  281  143  263  
1   58  116   87  257  293  338  
2  125  204  363  127  210  168  
3  335  181   22   49   32  275  
4  350  154  199  194  300  216  

[5 rows x 40 columns]

In [111]:
(df.nunique(axis = 1) < 40).mean()

0.887