In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [4]:
rng = np.random.default_rng(seed = 42)

1. How likely is it that you roll doubles when rolling two dice?

In [45]:
rolls = rng.choice([1, 2, 3, 4, 5, 6], 10_000 * 2).reshape(10_000, 2)
rolls

array([[1, 5],
       [4, 3],
       [3, 6],
       ...,
       [5, 1],
       [1, 3],
       [3, 3]])

In [46]:
doubles = (rolls[:, 1] == rolls[:, 0]).sum()

In [47]:
doubles / len(rolls)

0.1712

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

   What is the probability of getting more than 3 heads?

In [48]:
#heads = 1
#tails = 0

flips = rng.choice([0, 1], 10_000 * 8).reshape(10_000, 8)
flips

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 0, 1]])

In [49]:
exactly_three = (flips.sum(axis=1) == 3).sum()
exactly_three

2201

In [50]:
exactly_three / len(flips)

0.2201

In [51]:
heads = (flips.sum(axis=1) > 3).sum()
heads

6398

In [52]:
heads / len(flips)

0.6398

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [128]:
c = rng.random(2, (1_000, 2))
c

TypeError: Cannot interpret '1000' as a data type

In [72]:
d = (w >= .25).sum()
d

2973

In [73]:
d / len(c)

2.973

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [97]:
c = (rng.normal(3, 1.5, (1_000, 4))).sum(axis=1)
c

array([10.273559  , 13.82704661, 16.21067245,  8.52205238, 10.4688242 ,
       14.5783149 , 13.72536203, 10.39774031, 13.53221748, 13.07585963,
       17.72075823,  8.38219715, 16.54528834, 13.87476784, 11.32697626,
       12.59423498, 12.2049107 ,  8.6494572 , 14.07520353, 12.24439082,
       12.99795389, 12.34345276, 16.95693731,  5.00968828, 14.08239946,
        9.91613226,  9.22733085, 12.79882784, 12.65240533, 12.2136151 ,
       11.25037315, 14.34388794, 11.02290675, 15.00354299, 15.84085651,
        5.64351571, 11.0553525 , 13.52033723,  8.58953902, 17.57712025,
       16.09636686, 13.49296952,  9.59049912, 11.88455782, 13.45786112,
        8.3465016 , 17.51927727, 17.02886205, 18.91938961, 10.12425014,
       11.7307743 , 10.46464275,  9.29833328, 11.91282236, 17.1363854 ,
       11.9109296 , 12.17013496, 16.40731369,  9.39971927,  9.19575093,
       12.24767813,  7.77351818, 11.23215219,  8.78241721,  9.54391645,
       16.08931531,  9.78574511, 13.41362085,  9.37366776,  5.69

In [100]:
r = 17 - c
r 

array([ 6.72644100e+00,  3.17295339e+00,  7.89327548e-01,  8.47794762e+00,
        6.53117580e+00,  2.42168510e+00,  3.27463797e+00,  6.60225969e+00,
        3.46778252e+00,  3.92414037e+00, -7.20758234e-01,  8.61780285e+00,
        4.54711663e-01,  3.12523216e+00,  5.67302374e+00,  4.40576502e+00,
        4.79508930e+00,  8.35054280e+00,  2.92479647e+00,  4.75560918e+00,
        4.00204611e+00,  4.65654724e+00,  4.30626919e-02,  1.19903117e+01,
        2.91760054e+00,  7.08386774e+00,  7.77266915e+00,  4.20117216e+00,
        4.34759467e+00,  4.78638490e+00,  5.74962685e+00,  2.65611206e+00,
        5.97709325e+00,  1.99645701e+00,  1.15914349e+00,  1.13564843e+01,
        5.94464750e+00,  3.47966277e+00,  8.41046098e+00, -5.77120251e-01,
        9.03633145e-01,  3.50703048e+00,  7.40950088e+00,  5.11544218e+00,
        3.54213888e+00,  8.65349840e+00, -5.19277272e-01, -2.88620451e-02,
       -1.91938961e+00,  6.87574986e+00,  5.26922570e+00,  6.53535725e+00,
        7.70166672e+00,  

In [101]:
(r >= 0).mean()

0.934

5. Compare Heights

* Men have an average height of 178 cm and standard deviation of 8cm.

* Women have a mean of 170, sd = 6cm.

* Since you have means and standard deviations, you can use np.random.normal to generate observations.

* If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [108]:
m = (rng.normal(178, 8, 1_000))
m

array([177.18583401, 181.14838615, 178.70231565, 190.95526543,
       176.40112577, 184.72153993, 180.46150122, 167.72196322,
       183.18393217, 181.77970786, 169.63257297, 163.59000171,
       183.04385949, 178.85422781, 174.48768895, 176.85467168,
       184.59612188, 171.03243232, 173.88564926, 179.64057771,
       182.11345474, 181.0316382 , 196.51565261, 181.66317933,
       186.04605618, 156.56785929, 193.50452933, 187.65727269,
       164.59212283, 167.39689963, 176.70282272, 180.34753123,
       184.10477668, 182.51602604, 168.27822398, 179.69451697,
       184.43948537, 176.21861614, 176.32003801, 185.89224577,
       172.54497682, 172.39000215, 183.79811025, 175.27483256,
       185.18476356, 169.56243559, 175.69523349, 174.87486635,
       189.67879105, 172.65470857, 181.37094125, 177.86388033,
       175.0606712 , 187.21719075, 183.60241242, 183.59825525,
       177.08840312, 177.27513039, 186.45704061, 189.17794694,
       175.85637031, 174.73585674, 167.60852686, 169.74

In [109]:
w = (rng.normal(170, 6, 1_000))
w

array([176.12273421, 163.51464256, 166.00611516, 165.92369078,
       168.84038139, 162.55734925, 170.7737636 , 170.79881643,
       165.13752832, 171.06910715, 161.28167436, 160.14368578,
       176.3854459 , 164.24031377, 175.41995332, 169.71345894,
       173.19954857, 179.26800866, 161.68091743, 169.83130705,
       167.20277862, 167.53861561, 170.31443643, 163.88214722,
       164.62233391, 168.16080728, 163.23803091, 168.94868851,
       174.84399587, 165.10465325, 171.20548362, 170.33649064,
       167.4875585 , 181.83291082, 172.29411205, 165.49214194,
       171.55708928, 172.14870538, 171.4861074 , 174.55187594,
       171.78450368, 164.5175634 , 173.89781439, 180.17030107,
       178.12487173, 156.24092494, 166.20742935, 171.05422447,
       164.10824673, 169.17396777, 180.17404804, 179.31944279,
       167.21504586, 160.76643738, 165.74466953, 172.69289949,
       178.64598239, 178.61873283, 172.21010805, 168.80339954,
       169.2284793 , 184.86302565, 160.19077854, 174.28

In [112]:
wt = (w > m).sum()
wt

204

In [113]:
wt / len(w)

0.204

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

* What is the probability that we observe an installation issue within the first 150 students that download anaconda?

* How likely is it that 450 students all download anaconda without an issue?

In [119]:
c = 1 / 250
c

0.004

In [118]:
s = rng.random((1_000, 50))
s

array([[0.23313196, 0.90550833, 0.97848539, ..., 0.2127313 , 0.89883629,
        0.74967658],
       [0.13292695, 0.78032534, 0.66365668, ..., 0.89071938, 0.04556933,
        0.86171193],
       [0.52084336, 0.85205339, 0.97155204, ..., 0.69769369, 0.54582741,
        0.13822842],
       ...,
       [0.12939877, 0.93435963, 0.11856689, ..., 0.43111952, 0.25509202,
        0.04265694],
       [0.1416517 , 0.66285725, 0.97342199, ..., 0.93129395, 0.42621295,
        0.97574983],
       [0.39527024, 0.78515601, 0.31773166, ..., 0.92725143, 0.46802445,
        0.72271031]])

In [123]:
ic = (s <= c).sum()
ic

199

In [125]:
100 - ic / len(s)

99.801

In [ ]:
1